services:
  user-service-1:
    build: ./user-service-1
    ports:
      - "3001:3000"

  user-service-2:
    build: ./user-service-2
    ports:
      - "3002:3000"

  product-service:
    build: ./product-service
    ports:
      - "3003:3000"

  order-service:
    build: ./order-service
    ports:
      - "3004:3000"

  api-gateway:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    depends_on:
      - user-service-1
      - user-service-2
      - product-service
      - order-service
